import { Download, LoaderCircle, Database } from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {useOceanStore, type RightTab} from '../store/oceanStore';
import {instruments,profiles} from '../data/mockOceanData';
import {metrics} from '../utils/metrics';
import {exportCSV} from '../utils/exportReport';
import {useEffect,useState} from 'react';
const API='https://oceanvista-backend.onrender.com'; const tabs:RightTab[]=['PROFILE','MODEL VS OBSERVATION','QUALITY'];

type Real={rows:any[];metrics:any;instrument:any;match:any;source:string}|null;
export default function RightPanel(){
 const s=useOceanStore(); const obsDataset=s.argoDataset||s.observationDataset; const [plist,setPlist]=useState<any[]>([]); const [real,setReal]=useState<Real>(null); const [loading,setLoading]=useState(false); const [err,setErr]=useState('');
 useEffect(()=>{if(!obsDataset)return; fetch(`${API}/api/datasets/${obsDataset.id}/profiles?variable=${encodeURIComponent(s.variable)}`).then(r=>r.json()).then(d=>{if(d.profiles){setPlist(d.profiles); const p=d.profiles[Math.min(s.selectedProfileIndex,d.profiles.length-1)]; if(p)s.set('instrumentId',p.id)}}).catch(()=>setPlist([]))},[obsDataset?.id,s.variable]);
 useEffect(()=>{if(!s.modelDataset||!obsDataset||s.instrument!=='Argo Float'){setReal(null);return} setLoading(true);setErr(''); fetch(`${API}/api/validation/profile?model_id=${encodeURIComponent(s.modelDataset.id)}&argo_id=${encodeURIComponent(obsDataset.id)}&profile_index=${s.selectedProfileIndex}&variable=${encodeURIComponent(s.variable)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.detail||'Validation failed');return d}).then(setReal).catch(e=>{setErr(e.message);setReal(null)}).finally(()=>setLoading(false))},[s.modelDataset?.id,obsDataset?.id,s.selectedProfileIndex,s.variable,s.instrument]);
 const fallbackInfo=instruments[s.instrumentId]||instruments['2903671']; const fallbackRows=profiles[s.instrumentId]||profiles['2903671']; const rows=real?.rows||fallbackRows; const m=real?.metrics||metrics(rows); const info=real?.instrument||fallbackInfo;
 const exportNow=()=>exportCSV(s.instrumentId,rows,m);
 return <aside className="right panel"><section className="section instrument"><h3>SELECTED INSTRUMENT</h3>
  <div className="tabs"><button className={s.instrument==='Argo Float'?'active':''} onClick={()=>s.set('instrument','Argo Float')}>Argo Float</button><button className={s.instrument==='Glider'?'active':''} onClick={()=>{s.set('instrument','Glider');setReal(null)}}>Glider</button></div>
  {obsDataset&&s.instrument==='Argo Float'&&<div className="real-select"><Database size={14}/><select value={s.selectedProfileIndex} onChange={e=>{const i=Number(e.target.value);s.set('selectedProfileIndex',i);const p=plist[i];if(p)s.set('instrumentId',p.id)}}>{plist.map((p,i)=><option key={i} value={i}>{p.id} — {p.latitude?.toFixed?.(2)},{p.longitude?.toFixed?.(2)}</option>)}</select></div>}
  <div className="insthead"><span>● {info.type||'Argo Float'} <b>{real?.instrument?.id||s.instrumentId}</b></span><i>● Active</i></div>
  <dl><dt>Latitude</dt><dd>{Number(info.latitude??info.lat??0).toFixed(2)}° N</dd><dt>Longitude</dt><dd>{Number(info.longitude??info.lon??0).toFixed(2)}° E</dd><dt>Date & Time</dt><dd>{real?.instrument?.time||'12 Aug 2026 06:00 UTC'}</dd><dt>Max Depth</dt><dd>{Number(info.max_depth??info.maxDepth??0).toFixed(0)} m</dd><dt>Variables</dt><dd>{real?'Uploaded dataset':'Temp, Salinity, Chlorophyll'}</dd><dt>Quality Flag</dt><dd className="good">{real?'Calculated':'Good'}</dd></dl>
  {loading&&<div className="real-status"><LoaderCircle className="spin" size={15}/> Matching real model and Argo data…</div>}{real&&<div className="real-status good"><Database size={15}/> REAL UPLOADED DATA — {real.match.method}</div>}{err&&<div className="upload-error">{err}</div>}
 </section><section className="section chartsec"><div className="tabs tri">{tabs.map(t=><button key={t} className={s.rightTab===t?'active':''} onClick={()=>s.set('rightTab',t)}>{t}</button>)}</div>
 {s.rightTab==='PROFILE'&&<Profile rows={rows} real={!!real}/>} {s.rightTab==='MODEL VS OBSERVATION'&&<Comparison rows={rows} variable={s.variable} m={m} real={!!real}/>} {s.rightTab==='QUALITY'&&<Quality rows={rows} m={m} info={info} real={!!real}/>} 
 <button className="export" onClick={exportNow}><Download size={15}/> Export {real?'Real':'Validation'} Report</button></section></aside>
}
function ScientificChart({rows,showModel,showObserved}:{rows:any[];showModel:boolean;showObserved:boolean}){return <div className="chart"><ResponsiveContainer><LineChart data={rows} margin={{top:10,right:10,bottom:5,left:0}}><XAxis type="number" dataKey="observed" domain={['auto','auto']} tick={{fill:'#94a3b8',fontSize:10}}/><YAxis dataKey="depth" type="number" reversed domain={['auto','auto']} tick={{fill:'#94a3b8',fontSize:10}}/><Tooltip/><Legend/>{showModel&&<Line name="Model" dataKey="model" stroke="#f6b73c" strokeWidth={2} dot={false}/>} {showObserved&&<Line name="Observed" dataKey="observed" stroke="#38bdf8" strokeWidth={2} dot={{r:2}}/>}</LineChart></ResponsiveContainer></div>}
function Profile({rows,real}:{rows:any[];real:boolean}){return <><h2>{real?'Real Observed Profile':'Observed Profile'}</h2><ScientificChart rows={rows} showModel={false} showObserved={true}/><p className="panel-note">{real?'Values are extracted from the uploaded Argo dataset.':'Demo values until both real datasets are uploaded.'}</p><DataTable rows={rows}/></>}
function Comparison({rows,variable,m,real}:{rows:any[];variable:string;m:any;real:boolean}){return <><h2>{variable}</h2><ScientificChart rows={rows} showModel showObserved/>{real&&<p className="panel-note good">Real Argo observations matched to nearest model latitude/longitude/time and interpolated by depth.</p>}<DataTable rows={rows}/><h2>Validation Metrics</h2><div className="metrics"><Metric n="Bias" v={`${Number(m.bias).toFixed(2)}`}/><Metric n="MAE" v={`${Number(m.mae).toFixed(2)}`}/><Metric n="RMSE" v={`${Number(m.rmse).toFixed(2)}`}/><Metric n="Correlation" v={Number(m.correlation).toFixed(2)}/></div></>}
function Quality({rows,m,info,real}:{rows:any[];m:any;info:any;real:boolean}){const maxDiff=Math.max(...rows.map(r=>Math.abs(r.model-r.observed)));return <><h2>Quality Assessment</h2><div className="quality-summary"><b className="good">{real?'Calculated from real data':info.quality||'Good'}</b><span>{real?'Uploaded model vs Argo profile':'Demo profile validation'}</span></div><div className="quality-grid"><div><small>Samples</small><b>{rows.length}</b></div><div><small>Max Difference</small><b>{maxDiff.toFixed(2)}</b></div><div><small>RMSE</small><b>{Number(m.rmse).toFixed(2)}</b></div><div><small>Correlation</small><b>{Number(m.correlation).toFixed(2)}</b></div></div><DataTable rows={rows}/></>}
function DataTable({rows}:{rows:any[]}){return <table><thead><tr><th>Depth (m)</th><th>Observed</th><th>Model</th><th>Diff</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.depth}-${i}`}><td>{Number(r.depth).toFixed(0)}</td><td>{Number(r.observed).toFixed(2)}</td><td>{Number(r.model).toFixed(2)}</td><td>{Number(r.model-r.observed).toFixed(2)}</td></tr>)}</tbody></table>}
function Metric({n,v}:{n:string;v:string}){return <div><small>{n}</small><b>{v}</b></div>}
