import { Upload, X, FileCheck2, LoaderCircle, Database, AlertTriangle } from 'lucide-react';
import { useState } from 'react';
import { useOceanStore } from '../store/oceanStore';
const API='http://127.0.0.1:8000'; type Kind='model'|'argo'|'observation';
export default function UploadDataset(){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<Kind>('model'),[file,setFile]=useState<File|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null); const s=useOceanStore();
 const upload=async()=>{if(!file)return;setLoading(true);setError('');try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/api/datasets/upload/${kind}`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Upload failed');setResult(d); if(d.validation.valid){const info={id:d.dataset_id,filename:d.filename,variables:d.metadata.variables||[],source:'Validated uploaded '+kind+' dataset',metadata:d.metadata}; if(kind==='model'){s.set('uploadedDataset',info);s.set('modelDataset',info);s.set('modelField',null)} if(kind==='argo'){s.set('argoDataset',info);s.set('instrument','Argo Float');s.set('selectedProfileIndex',0)} if(kind==='observation'){s.set('observationDataset',info);s.set('instrument','Argo Float');s.set('selectedProfileIndex',0)} if(kind==='model' && d.metadata?.times){s.set('dataTimes',d.metadata.times);s.set('timeIndex',0)} }}catch(e:any){setError(`${e.message}. Make sure FastAPI is running on port 8000.`)}finally{setLoading(false)}};
 return <><button className="upload-trigger" onClick={()=>{setOpen(true);setResult(null)}}><Upload size={15}/> Scientific Data Workspace</button>{s.modelDataset&&<div className="upload-status"><FileCheck2 size={14}/><span>Model: {s.modelDataset.filename}</span></div>}{s.argoDataset&&<div className="upload-status"><FileCheck2 size={14}/><span>Argo: {s.argoDataset.filename}</span></div>}{s.observationDataset&&<div className="upload-status"><FileCheck2 size={14}/><span>Obs: {s.observationDataset.filename}</span></div>}
 {open&&<div className="modalback"><div className="modal upload-modal"><button className="close" onClick={()=>!loading&&setOpen(false)}><X/></button><h2><Database size={19}/> Load Scientific Data</h2><p>Upload real datasets. OceanVista validates coordinates, dimensions, variables and missing values before visualization.</p>
 <div className="upload-tabs">{(['model','argo','observation'] as Kind[]).map(k=><button className={kind===k?'active':''} onClick={()=>{setKind(k);setFile(null);setResult(null);setError('')}} key={k}>{k==='model'?'① Model NetCDF':k==='argo'?'② Argo NetCDF':'③ CSV / ASCII'}</button>)}</div>
 <p className="panel-note">{kind==='model'?'Required: latitude, longitude, depth, time and numeric scientific variables.':kind==='argo'?'Reads real float/profile coordinates, depth, time and available scientific variables.':'CSV, TXT or ASCII observations with detectable coordinate columns.'}</p>
 <input type="file" accept={kind==='observation'?'.csv,.txt,.asc,.ascii,.nc,.nc4,.cdf':'.nc,.nc4,.cdf'} onChange={e=>{setFile(e.target.files?.[0]||null);setResult(null)}}/>{file&&<div className="file-name">Selected: {file.name}</div>}{error&&<div className="upload-error"><AlertTriangle size={15}/>{error}</div>}
 {!result?<button className="export" disabled={!file||loading} onClick={upload}>{loading?<LoaderCircle className="spin" size={16}/>:<Upload size={16}/>}{loading?'Validating...':'Upload & Validate'}</button>:<div className={result.validation.valid?'validation goodbox':'validation badbox'}><b>{result.validation.valid?'✓ DATASET READY':'⚠ DATASET INVALID'}</b><span>{result.filename}</span><div className="meta-grid"><span>Variables <b>{result.metadata.variables?.length||0}</b></span><span>Dimensions <b>{result.metadata.dimensions?.length||0}</b></span></div>{result.validation.errors?.map((x:string)=><small key={x}>• {x}</small>)}<button className="export" onClick={()=>result.validation.valid?setOpen(false):setResult(null)}>{result.validation.valid?'Continue to Dashboard':'Choose Another File'}</button></div>}</div></div>}</>;
}
