import {Camera,Share2,Ruler,Settings,HelpCircle,X,Check} from 'lucide-react';import {useState} from 'react';import {useOceanStore} from '../store/oceanStore';
export default function Toolbar(){const [modal,setModal]=useState<string|null>(null);const s=useOceanStore();
const shot=()=>{const c=document.querySelector('.scene canvas') as HTMLCanvasElement|null;if(!c)return alert('Visualization is not ready');try{const a=document.createElement('a');a.download='oceanvista-scene.png';a.href=c.toDataURL('image/png');a.click()}catch{alert('Screenshot capture failed')}};
const share=async()=>{const state=encodeURIComponent(JSON.stringify({region:s.region,variable:s.variable,depth:s.depth,mode:s.mode}));const url=location.origin+location.pathname+'#state='+state;try{await navigator.clipboard.writeText(url);alert('Shareable dashboard state copied')}catch{prompt('Copy this link:',url)}};
const toggleMeasure=()=>{s.set('measureMode',!s.measureMode);s.set('measurePoints',[]);if(!s.measureMode)alert('Measurement mode enabled. Click two points in the 3D scene.')};
let measure='Click two points';if(s.measurePoints.length===2){const [a,b]=s.measurePoints;const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2];measure=`Distance: ${Math.sqrt(dx*dx+dy*dy+dz*dz).toFixed(2)} scene units · Depth Δ: ${Math.abs(dy/6*2000).toFixed(0)} m`}
return <><div className="toolbar"><button onClick={shot}><Camera/><small>Screenshot</small></button><button onClick={share}><Share2/><small>Share</small></button><button className={s.measureMode?'active':''} onClick={toggleMeasure}><Ruler/><small>Measure</small></button><button onClick={()=>setModal('Settings')}><Settings/><small>Settings</small></button><button onClick={()=>setModal('Help')}><HelpCircle/><small>Help</small></button></div>
{s.measureMode&&<div className="measure-readout">{measure}</div>}
{modal&&<div className="modalback"><div className="modal"><button className="close" onClick={()=>setModal(null)}><X/></button><h2>{modal}</h2>{modal==='Settings'?<><label>Animation quality<select defaultValue="Balanced"><option>High</option><option>Balanced</option><option>Performance</option></select></label><label>Default visualization mode<select value={s.mode} onChange={e=>s.set('mode',e.target.value as any)}><option>3D Volume</option><option>Depth Slice</option><option>Isosurface</option></select></label><label>Data refresh interval<select><option>5 seconds</option><option>15 seconds</option><option>60 seconds</option></select></label><button className="export" onClick={()=>{localStorage.setItem('oceanvista-settings',JSON.stringify({mode:s.mode}));setModal(null)}}><Check size={16}/> Save Settings</button></>:<><h3>Navigation</h3><p>Drag to rotate, scroll to zoom, and right-drag to pan.</p><h3>Real data</h3><p>Upload Model NetCDF and Argo NetCDF, then select an Argo profile to calculate real model-versus-observation results.</p><h3>Modes</h3><p>3D Volume shows the uploaded model field; Depth Slice follows the selected depth; Isosurface is a safe animated scientific threshold view.</p></>}</div></div>}</>}
