import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, Line, Html, Edges } from '@react-three/drei';
import * as THREE from 'three';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import { useOceanStore } from '../store/oceanStore';

const API='http://127.0.0.1:8000', W=10,H=6,D=7;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const depthY=(depth:number)=>H/2-clamp(depth,0,2000)/2000*H;
function palette(t:number,scale:string){const sets:any={Turbo:['#30123b','#4145ab','#20b7d2','#30c979','#b8df2c','#ffe11a','#ff7a16','#d7191c'],Viridis:['#440154','#482878','#31688e','#26828e','#35b779','#b5de2b','#fde725'],Plasma:['#0d0887','#6a00a8','#b12a90','#e16462','#fca636','#f0f921'],Inferno:['#000004','#420a68','#932667','#dd513a','#fca50a','#fcffa4'],'Cool Warm':['#3b4cc0','#6aaed6','#b9d6e8','#f7f7f7','#f7b89c','#e26952','#b40426']};const a=sets[scale]||sets.Turbo,x=clamp(t,0,.99999)*(a.length-1),i=Math.floor(x);return new THREE.Color(a[i]).lerp(new THREE.Color(a[Math.min(i+1,a.length-1)]),x-i)}
class SceneErrorBoundary extends React.Component<{children:React.ReactNode},{bad:boolean}>{state={bad:false};static getDerivedStateFromError(){return {bad:true}}render(){return this.state.bad?<div className="scene-error">3D renderer recovered safely. Choose another mode or dataset.</div>:this.props.children}}
function WaterSurface(){const ref=useRef<THREE.Mesh>(null!),geo=useMemo(()=>new THREE.PlaneGeometry(W,D,72,52),[]);useFrame(({clock})=>{const p=geo.attributes.position as THREE.BufferAttribute,t=clock.elapsedTime;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i);p.setZ(i,.07*Math.sin(x*1.45+t*.9)+.04*Math.cos(z*2.1-t*.6)+.02*Math.sin((x+z)*3.1+t*.4))}p.needsUpdate=true;if(Math.floor(t*8)%2===0)geo.computeVertexNormals();});return <mesh ref={ref} geometry={geo} rotation={[-Math.PI/2,0,0]} position={[0,H/2+.03,0]}><meshPhysicalMaterial color="#07567a" emissive="#04233a" emissiveIntensity={.65} roughness={.1} metalness={.78} transparent opacity={.93}/></mesh>}
function RealField(){const s=useOceanStore(),[err,setErr]=useState('');useEffect(()=>{if(!s.modelDataset?.id){s.set('modelField',null);return}let dead=false,c=new AbortController();fetch(`${API}/api/datasets/${encodeURIComponent(s.modelDataset.id)}/field?variable=${encodeURIComponent(s.variable)}&time_index=${s.timeIndex}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||'Field unavailable');return d}).then(d=>{if(!dead&&Array.isArray(d.values)&&d.values.length){s.set('modelField',d);if(Number.isFinite(d.min)&&Number.isFinite(d.max)&&d.max>d.min){s.set('colorMin',d.min);s.set('colorMax',d.max)}if(Array.isArray(d.times)&&d.times.length)s.set('dataTimes',d.times)}}).catch(e=>{if(e.name!=='AbortError'){setErr(e.message);if(!dead)s.set('modelField',null)}});return()=>{dead=true;c.abort()}},[s.modelDataset?.id,s.variable,s.timeIndex]);return err?<Html position={[0,0,0]}><div className="scene-toast">Dataset field: {err}</div></Html>:null}
function FieldPoints(){const s=useOceanStore(),f=s.modelField;const geom=useMemo(()=>{if(!f?.shape||!Array.isArray(f.values))return null;const {nx,ny,nz}=f.shape;if(!nx||!ny||!nz||nx*ny*nz!==f.values.length)return null;const pos=new Float32Array(f.values.length*3),col=new Float32Array(f.values.length*3);let k=0;const lo=s.colorMin,hi=Math.max(lo+1e-8,s.colorMax);for(let z=0;z<nz;z++)for(let y=0;y<ny;y++)for(let x=0;x<nx;x++,k++){pos[3*k]=(x/Math.max(1,nx-1)-.5)*W;pos[3*k+1]=H/2-z/Math.max(1,nz-1)*H;pos[3*k+2]=(y/Math.max(1,ny-1)-.5)*D;let t=(Number(f.values[k])-lo)/(hi-lo);if(s.log)t=Math.log1p(9*clamp(t,0,1))/Math.log(10);const c=palette(t,s.colorScale);col.set([c.r,c.g,c.b],3*k)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));return g},[f,s.colorScale,s.colorMin,s.colorMax,s.log]);useEffect(()=>()=>geom?.dispose(),[geom]);if(!geom)return null;return <points geometry={geom} scale={[1,s.vertical,1]}><pointsMaterial size={.105} vertexColors transparent opacity={Math.min(.95,s.opacity*.86)} sizeAttenuation depthWrite={false}/></points>}
function FallbackVolume(){const s=useOceanStore();return <group scale={[1,s.vertical,1]}>{Array.from({length:42},(_,i)=>{const q=i/41;const warm=1-q;const c=palette(warm,s.colorScale);return <mesh key={i} position={[0,H/2-q*H,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[W-.1,D-.1,1,1]}/><meshBasicMaterial color={c} transparent opacity={(.018+.075*Math.sin(q*Math.PI))*s.opacity} depthWrite={false} side={THREE.DoubleSide}/></mesh>})}</group>}
function OceanVolume(){const s=useOceanStore();return <group><mesh scale={[1,s.vertical,1]}><boxGeometry args={[W,H,D]}/><meshPhysicalMaterial color="#0b4264" transparent opacity={.055} depthWrite={false} side={THREE.DoubleSide}/><Edges color="#2c8ac0" transparent opacity={.85}/></mesh>{s.layers['Numerical Model']&&(s.modelField?<FieldPoints/>:<FallbackVolume/>)}<WaterSurface/></group>}
function Argo(){const s=useOceanStore();if(!s.layers['Argo Floats'])return null;const ids=['2903671','2904120','2905214','2906382'];return <group>{ids.map((id,i)=>{const p:[number,number,number]=[-3+i*2.05,(H/2-.08)*s.vertical,(i%2?1:-1)*1.25],a=s.instrumentId===id;return <group key={id} position={p} onClick={e=>{e.stopPropagation();s.set('instrument','Argo Float');s.set('instrumentId',id)}}><mesh><sphereGeometry args={[a?.19:.12,20,20]}/><meshStandardMaterial color={a?'#d8f7ff':'#198bdf'} emissive="#0876b4" emissiveIntensity={a?2.4:.8}/></mesh><mesh position={[0,-1.55*s.vertical,0]}><cylinderGeometry args={[.02,.02,3.1*s.vertical,6]}/><meshBasicMaterial color="#70dcff" transparent opacity={.8}/></mesh>{a&&<Html position={[.32,.28,.1]} distanceFactor={8}><div className="scene-label"><span>Argo Float</span><b>{id}</b></div></Html>}</group>})}</group>}
function Glider(){const s=useOceanStore(),r=useRef<THREE.Group>(null!);useFrame(({clock})=>{if(r.current)r.current.position.x=.18*Math.sin(clock.elapsedTime*.55)});if(!s.layers.Gliders)return null;const pts=[[-2.2,2.3,2.4],[-1.5,1.7,1.8],[-.7,1,1],[.1,.25,.25],[.9,-.45,-.45],[1.7,-1.1,-1.1],[2.5,-1.7,-1.7]] as [number,number,number][];return <group ref={r} scale={[1,s.vertical,1]} onClick={e=>{e.stopPropagation();s.set('instrument','Glider');s.set('instrumentId','SG678')}}><Line points={pts} color="#ef5cf5" lineWidth={2}/>{pts.map((p,i)=><mesh key={i} position={p}><sphereGeometry args={[.055,12,12]}/><meshBasicMaterial color="#ff87f4"/></mesh>)}<Html position={pts[1]} distanceFactor={8}><div className="scene-label mag"><span>Glider</span><b>SG678</b></div></Html></group>}
function Currents(){const s=useOceanStore(),g=useRef<THREE.Group>(null!);useFrame(({clock})=>{if(g.current)g.current.position.x=.12*Math.sin(clock.elapsedTime*.4)});if(!s.layers.Currents)return null;return <group ref={g}>{Array.from({length:28},(_,i)=>{const x=-4.5+(i%7)*1.5,z=-2.7+Math.floor(i/7)*1.75,a=i*.73,e:[number,number,number]=[x+.52*Math.cos(a),2.7,z+.52*Math.sin(a)];return <group key={i}><Line points={[[x,2.7,z],e]} color="#75dcff"/><mesh position={e} rotation={[0,a-Math.PI/2,0]}><coneGeometry args={[.07,.18,7]}/><meshBasicMaterial color="#b5efff"/></mesh></group>})}</group>}
function DepthSlice(){const s=useOceanStore();if(s.mode!=='Depth Slice')return null;const y=depthY(s.depth)*s.vertical;const t=s.modelField?.depth?.length?clamp(s.depth/Math.max(1,Number(s.modelField.depth.at(-1)||2000)),0,1):s.depth/2000;return <group position={[0,y,0]}><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[W-.12,D-.12,42,30]}/><meshBasicMaterial color={palette(1-t,s.colorScale)} transparent opacity={.72} side={THREE.DoubleSide}/></mesh><Line points={[[-W/2,0,-D/2],[W/2,0,-D/2],[W/2,0,D/2],[-W/2,0,D/2],[-W/2,0,-D/2]]} color="#79eaff"/><Html position={[3.1,.18,1.7]} distanceFactor={8}><div className="scene-label"><span>Depth Slice</span><b>{s.depth===0?'Surface':`${s.depth} m`}</b></div></Html></group>}
function Isosurface(){const s=useOceanStore();const geo=useMemo(()=>{const nx=52,ny=36,verts:number[]=[];for(let j=0;j<=ny;j++)for(let i=0;i<=nx;i++){const u=i/nx-.5,v=j/ny-.5;const r=1+.18*Math.sin(i*.31)*Math.cos(j*.23)+.08*Math.sin((i+j)*.19);verts.push(u*4.2*r,v*1.8*r,.28*Math.sin(i*.22)+.18*Math.cos(j*.35)+.18*Math.sin((i-j)*.14))}const idx:number[]=[];for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const a=j*(nx+1)+i,b=a+1,c=a+(nx+1),d=c+1;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g},[]);useEffect(()=>()=>geo.dispose(),[geo]);if(s.mode!=='Isosurface')return null;return <group scale={[1,s.vertical,1]}><mesh geometry={geo} position={[0,-1.65,0]} rotation={[-.2,.45,.08]}><meshStandardMaterial color="#27d590" emissive="#087850" emissiveIntensity={1.1} transparent opacity={.78} roughness={.35} metalness={.12} side={THREE.DoubleSide}/></mesh><Html position={[0,-.6,0]} distanceFactor={8}><div className="scene-label iso"><span>Isosurface</span><b>{s.variable.includes('Temperature')?'20°C':s.variable}</b></div></Html></group>}
function Bathymetry(){const s=useOceanStore();const geo=useMemo(()=>{const g=new THREE.PlaneGeometry(W-.12,D-.12,64,46);const p=g.attributes.position as THREE.BufferAttribute;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i),h=.42*Math.exp(-((x+1.2)**2+(z-.1)**2)/3)+.22*Math.sin(x*1.3)*Math.cos(z*1.8)+.08*Math.sin(z*4);p.setZ(i,h)}p.needsUpdate=true;g.computeVertexNormals();return g},[]);useEffect(()=>()=>geo.dispose(),[geo]);if(!s.layers.Bathymetry)return null;return <mesh geometry={geo} position={[0,-H/2*s.vertical+.08,0]} rotation={[-Math.PI/2,0,0]} scale={[1,s.vertical,1]}><meshStandardMaterial color="#0b5f63" emissive="#04383a" emissiveIntensity={.75} roughness={.82} transparent opacity={.96} side={THREE.DoubleSide}/></mesh>}
function MeasureLayer(){const s=useOceanStore(),p=s.measurePoints;if(p.length<2)return null;return <><Line points={[p[0],p[1]]} color="#facc15" lineWidth={2}/>{p.map((x,i)=><mesh key={i} position={x}><sphereGeometry args={[.1,12,12]}/><meshBasicMaterial color="#facc15"/></mesh>)}</>}
function ClickPlane(){const s=useOceanStore();return <mesh visible={s.measureMode} rotation={[-Math.PI/2,0,0]} position={[0,0,0]} onClick={e=>{if(!s.measureMode)return;e.stopPropagation();const p:[number,number,number]=[e.point.x,e.point.y,e.point.z];s.set('measurePoints',s.measurePoints.length>=2?[p]:[...s.measurePoints,p] as any)}}><planeGeometry args={[28,28]}/><meshBasicMaterial transparent opacity={0}/></mesh>}
function SceneCanvas(){return <Canvas camera={{position:[10.7,8.5,11.5],fov:39}} dpr={[1,1.5]} gl={{preserveDrawingBuffer:true,antialias:true}}><color attach="background" args={['#020812']}/><fog attach="fog" args={['#020812',13,30]}/><ambientLight intensity={.65}/><directionalLight position={[5,9,6]} intensity={1.55}/><pointLight position={[-4,3,3]} intensity={1} color="#075b99"/><RealField/><OceanVolume/><Bathymetry/><Argo/><Glider/><Currents/><DepthSlice/><Isosurface/><MeasureLayer/><ClickPlane/><OrbitControls enableDamping dampingFactor={.075} maxDistance={25} minDistance={6}/></Canvas>}
export default function OceanScene(){return <div className="scene"><SceneErrorBoundary><SceneCanvas/></SceneErrorBoundary><div className="geo-longitudes"><span>84°E</span><span>86°E</span><span>88°E</span><span>90°E</span></div><div className="geo-latitudes"><span>16°N</span><span>14°N</span><span>12°N</span></div><div className="geo-depth"><span>0 m</span><span>100 m</span><span>200 m</span><span>500 m</span><span>1000 m</span><span>2000 m</span></div><div className="endpoint a">A</div><div className="endpoint b">B</div><div className="cross"><span>Cross Section</span><b>A ───── B</b></div><div className="scene-hint">Drag to rotate · Scroll to zoom · Right drag to pan</div></div>}
